spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5480/eventstorming
    username: postgres
    password: postgres

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 9885

logging:
  level:
    root: OFF
    com:
      eventstorming: INFO
#    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE